<hr>
	<div>
            
        <p>Type the Author's (or Artist's) <strong>LAST NAME first</strong>, for example:</p>
        
		<ul>
			<li>Wilmerding</li>

			<li>Smith, Kiki</li>

			<li>Jones, Inigo </li>
		</ul>
                
        <p>You may also type the name of a museum or other organization, for example: </p>
        
            <ul>
                
                        <li>National Gallery</li>
                        
                        <li>University City Porcelain Works</li>
                        
                        <li>Wiener Werkst&#228;tte</li>
                        
	</div>
</div>
