<hr>
	<div>
            
        <p>Enter as much of the AUCTION HOUSE name as you know, in the same order in which it appears in the catalog, for example:</p>
        
		<ul>
			<li>Sotheby</li>
                        
                        <li>Hotel Drouot</li>
                        
                        <li>Ivey-Selkirk</li>

                        <li>Ader, Etienne <em>(enter individual auctioneers <strong>Last Name first</strong>)</em></li>

		</ul>
                
    