<hr>
	<div>
            
        <p>Type the Author's or Artist's LAST NAME first.</p>
        
		<ul>
			<li>Ewan</li>

			<li>Ewan, Joseph</li>

			<li>Raven, P</li>
                        
                        <li>hooker, j</li>
		</ul>
                
        <p>You may also type the name of an organization or governmental body.</p>
        
		<ul>
			<li>Botanical Society of America</li>

			<li>Missouri Botanical Garden</li>

		</ul>
                
                        
	</div>
</div>
