<hr>
	<div>
            
        <p>The Richardson Library uses Library of Congress call numbers. Use right-hand truncation, and type as much of the call number as you like, for example: </p>
        
		<ul>
			<li>ND653 G7 A4 2001</li>

			<li>ND653 G7</li>

			<li>N729 A7 2006</li>
                        
                        <li>N729 A7 2006</li>
		</ul>
                        
	</div>
</div>
