<hr>
	<div>
            
        <p>Use right-hand truncation, typing as much or as little of the <strong>TITLE</strong> as you want, for example:</p>
        
		<ul>
			<li>Out of this century</li>

			<li>Schilder-boek</li>

			<li>Maori</li>
		</ul>
                
        <p>Omit initial articles from titles in all languages (e.g. <em>A, The, Les, El,</em> etc.). </p>
                        
	</div>
</div>
