<hr>
	<div>
            
        <p>Use right-hand truncation, and type as much of the ISBN/ISSN as you want, with or without hyphens; for example:</p>
        
		<ul>
			<li>0197-1093 (ISSN)</li>

			<li>0197-1</li>

			<li>978-0-500-51318-7 (13-digit ISBN)</li>
                        
                        <li>9780500513</li>
                        
                        <li>050051318X (10-digit ISBN)</li>
                        
                        <li>0-500-51 </li>
		</ul>
                        
	</div>
</div>
