<hr>
	<div>
            
        <p>Type the exact <strong>Date of Sale</strong> as 8 digits, for example:</p>
        
		<ul>
			<li>2005 December 19 = <strong>20051219</strong></li>

		</ul>
                
        <p>Use right-hand truncation to retrieve all catalogs for an entire month, for example:</p>
        
            <ul>
                
                        <li>May 1998 = <strong>199805</strong> or <strong>1998/05</strong></li>
                        
            </ul>
            
        <p>For sales that occurred over a span of dates, enter the <strong>earliest</strong> date of sale, for example: </p>
        
            <ul>
                
                        <li>July 2-11, 2001 = <strong>20010702</strong> or <strong>2001/07/02</strong></li>
                        
            </ul>
                        
	</div>
</div>
