<hr>
	<div>
            
        <p>Use right-hand truncation, typing as much or as little of the <strong>JOURNAL TITLE</strong> as you want, for example: </p>
        
		<ul>
			<li>Journal of the history of collections</li>

			<li>Performing arts</li>

			<li>Gazette des beaux arts </li>
		</ul>
                
        <p>Omit <strong>initial</strong> articles in all languages (e.g. <em>A, The, Ein, Les, El</em>). </p>
                        
	</div>
</div>