<div class="mainMenuSrchText">
Type as much or as little of the journal, magazine, or newspaper title as you want. For example:

<ul>
<li>journal of counseling psychology</li>
<li>journal of counseling psy</li>
</ul>
<hr />

This search engine will find magazines, journals and newspapers which the libraries own. To find individual periodical articles, use periodical indexes or databases such as EBSCO, Gail, etc.


</div>
