<hr>
	<div>
            
        <p>Use right-hand truncation, typing as much or as little of the TITLE as you want, for example:</p>
        
		<ul>
			<li>Important silver, gold boxes and objects of vertu</li>
                        
                        <li>Important silver </li>
                        
        <p>Omit initial articles from titles in all languages (e.g. <em>A, The, Les, El</em>, etc.).</p>

		</ul>
                
    