<hr>
	<div>
            
        <p>Type as much or as little of the TITLE as you want, beginning with the first word. Omit any article at the beginning of the title ("the," "les," "el"...). You may also enter a BPH abbreviation as a title. </p>
        
		<ul>
			<li>History of Botany (1530-1860)</li>

			<li>History of Bot</li>

			<li>History</li>
                        
                        <li>nat. malays. </li>
		</ul>
                        
	</div>
</div>
